import mongoose from "mongoose";

const itineraryItemSchema = new mongoose.Schema(
  {
    day: { type: Number, required: true },
    startTime: { type: String },
    title: { type: String, required: true },
    listing: { type: mongoose.Schema.Types.ObjectId, ref: "Listing" },
    booking: { type: mongoose.Schema.Types.ObjectId, ref: "Booking" },
    notes: { type: String },
    locationName: { type: String },
    coordinates: { type: [Number] }, // [lng, lat]
    travelFromPrevious: {
      distanceMeters: Number,
      durationSeconds: Number,
      distanceText: String,
      durationText: String,
    },
    weather: {
      condition: String,
      tempMax: Number,
      tempMin: Number,
      rainProb: Number,
      icon: String,
      recommendation: String,
    },
  },
  { _id: false }
);

const dailyWeatherSchema = new mongoose.Schema(
  {
    day: Number,
    date: String,
    condition: String,
    tempMax: Number,
    tempMin: Number,
    rainProb: Number,
    icon: String,
    recommendation: String,
  },
  { _id: false }
);

const itinerarySchema = new mongoose.Schema(
  {
    tourist: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    title: { type: String, required: true },
    startDate: { type: Date, required: true },
    endDate: { type: Date, required: true },
    generatedByAI: { type: Boolean, default: false },
    // "draft": just generated by the AI assistant, awaiting the tourist's review.
    // "confirmed": the tourist reviewed it and explicitly saved/accepted it.
    status: { type: String, enum: ["draft", "confirmed"], default: "draft", index: true },
    acceptedAt: { type: Date },
    items: [itineraryItemSchema],
    dailyWeather: [dailyWeatherSchema],
    shareToken: { type: String, unique: true, sparse: true },
  },
  { timestamps: true }
);

export default mongoose.model("Itinerary", itinerarySchema);
